# Generated by Django 5.1.1 on 2024-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imfeeling",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="imfeeling",
            name="feeling_name",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Feeling Name"
            ),
            preserve_default=False,
        ),
    ]
