# Generated by Django 5.1.1 on 2024-12-01 16:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0004_prophetstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="prayer_images/")),
            ],
        ),
    ]
