# Generated by Django 5.1.1 on 2024-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0005_prayer"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="prayer",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
       
    ]
