# Generated by Django 5.1.1 on 2024-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0006_prayer_created_at_prayer_image_url_prayer_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="prayer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
