# Generated by Django 5.1.1 on 2024-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0007_prayer_created_at_prayer_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameOfAllah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
