# Generated by Django 5.1.1 on 2024-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0008_nameofallah"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameofallah",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="nameofallah",
            name="image",
            field=models.ImageField(default=1, upload_to="prayer_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nameofallah",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nameofallah",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
