# Generated by Django 5.1.1 on 2024-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0009_nameofallah_created_at_nameofallah_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameofallah",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
