# Generated by Django 5.1.1 on 2024-12-04 16:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0010_alter_nameofallah_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RamadanDua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("reference", models.CharField(max_length=255)),
            ],
        ),
    ]
