# Generated by Django 5.1.1 on 2024-12-05 16:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0011_ramadandua"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seerah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
                ("section", models.CharField(max_length=255)),
                ("subsection", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
