# Generated by Django 5.1.1 on 2024-12-05 18:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0014_familymember"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuhammadChildren",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="children_images/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
