# Generated by Django 5.1.1 on 2024-12-05 18:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0016_battle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
