# Generated by Django 5.1.1 on 2024-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0018_hadith"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurahContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
