# Generated by Django 5.1.1 on 2024-12-06 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0020_surah_surahtranslation_delete_surahcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surahtranslation",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
