# Generated by Django 5.1.1 on 2024-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0021_alter_surahtranslation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="battle_images/"),
        ),
        migrations.AddField(
            model_name="battle",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="familymember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="familymember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="hadith",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="hadith",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hadith_images/"),
        ),
        migrations.AddField(
            model_name="hadith",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hadith",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="muhammadchildren",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="muhammadchildren",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="seerah",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="seerah",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="seerah_images/"),
        ),
        migrations.AddField(
            model_name="seerah",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seerah",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="wife",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="wife",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="wife_images/"),
        ),
        migrations.AddField(
            model_name="wife",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wife",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
