# Generated by Django 5.1.1 on 2024-12-14 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0023_imfeeling_created_at_imfeeling_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ramadandua",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ramadandua",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
