# Generated by Django 5.1.1 on 2024-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0024_ramadandua_created_at_ramadandua_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="duadhikr",
            name="image",
            field=models.ImageField(default=1, upload_to="prayer_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="duadhikr",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ramadandua",
            name="image",
            field=models.ImageField(default=1, upload_to="prayer_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ramadandua",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
