# Generated by Django 5.1.1 on 2025-01-03 17:16

import ImfeelingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImfeelingApp", "0026_playlist_videoplaylist"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoplaylist",
            name="uploaded_by",
            field=models.JSONField(
                default=ImfeelingApp.models.default_json_uploaded_by
            ),
        ),
    ]
